name: Java maven environment setup

description: "empty"

inputs:
  java-version:
    required: false
    description: "empty"
    default: '21'
  distribution:
    required: false
    description: "empty"
    default: 'temurin'
  settings_xml:
    required: false
    description: "Contenu du fichier settings.xml à utiliser pour Maven"
    default: ''

runs:
  using: "composite"
  steps:
    - name: Setup java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: 'maven'

    - name: Setup maven
      if: ${{ inputs.settings_xml != '' }}
      shell: bash
      run: echo "${{ inputs.settings_xml }}" > /home/runner/.m2/settings.xml
#      run: cp -fr ${GITHUB_ACTION_PATH}/settings.xml  /home/runner/.m2/settings.xml