name: Git bot user setup

description: "empty"

runs:
  using: "composite"
  steps:
    - name: Git configuration
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"