name: 'Generate Next Version'
description: 'Generate the next semantic version based on release type'

inputs:
  fallback_version:
    description: 'Fallback version if no previous tag exists'
    required: false
    default: '1.0.0'

outputs:
  version:
    description: 'The current version number (e.g., 1.2.3)'
    value: ${{ steps.select_version.outputs.version }}
  full_version:
    description: 'The current version with v prefix (e.g., v1.2.3)'
    value: ${{ steps.select_version.outputs.full_version }}

runs:
  using: 'composite'
  steps:
    - name: Get previous tag
      id: tag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      with:
        fallback: ${{ inputs.fallback_version }}

    - name: Strip v from tag
      id: select_version
      shell: bash
      run: |
        TAG="${{ steps.tag.outputs.tag }}"
        echo "full_version=${TAG}" >> $GITHUB_OUTPUT
        echo "version=${TAG#v}" >> $GITHUB_OUTPUT
