name: 'Docker Hub Setup'
description: 'Setup Docker Hub for publishing images'

inputs:
  dockerhub_username:
    description: 'Docker Hub username'
    required: true
  dockerhub_password:
    description: 'Docker Hub access token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_password }}